### ISSUE TITLE
way to turn off music?

### ISSUE THREAD

**Issue by Kyoumimasu** [sefinek24/Genshin-Impact-ReShade#14]
I was wondering if there was a way to turn off the music of the launcher? 
And is there a way to add a different background picture of one that I took of my favorite character?

Also, so I don't have to make another post: 
I had a suggestion for making the links/navigation a bit clearer? 
I have autism and dyslexia with a low vision disability to boot. 
The current screen is hard to understand and navigate. 
If the text and links were a bit more structured or easier to read it would help a lot. 
And color-wise, some are hard to see on the backgrounds provided. 
I've mis-clicked a lot trying to get into the game ^^;

**Comment by sefinek24** [comment]
> I was wondering if there was a way to turn off the music of the launcher?

Of course! This is possible. Just delete `music.wav` file from mod folder: `C:\Genshin-Impact-ReShade\data\music.wav`

> And is there a way to add a different background picture of one that I took of my favorite character?

Yes. Replace files in `C:\Genshin-Impact-ReShade\screenshots`.

> I had a suggestion for making the links/navigation a bit clearer?

If you want, you can create a new Pull Request and propose changes yourself.
Launcher repository: https://github.com/sefinek24/genshin-mod-launcher

> If the text and links were a bit more structured or easier to read it would help a lot.

That's true. I don't have time to take new screenshots from the latest version.

**Comment by Kyoumimasu** [comment]
Thank you! I'll look into these in the next 2 days when I get sometime. 
I appreciate the quick and straightforward response! 

If I come across some roadblock I'll ask about it ^^
