### ISSUE TITLE
GIMI Paywall?

### ISSUE THREAD

**Issue by Scarlaid** [sefinek24/Genshin-Impact-ReShade#36]
https://www.virustotal.com/gui/file/122d718df164d647842c56e0bbdc220e8bc9ad97d8816c700a39010d2ce0ec86?nocache=1
### ?
![image](https://github.com/sefinek24/Genshin-Impact-ReShade/assets/90851437/db00a406-fa96-4516-b667-b3b9bb318d05)
![image](https://github.com/sefinek24/Genshin-Impact-ReShade/assets/90851437/afcfa0d2-b957-49ff-ab3c-237fe3a5116a)

**Comment by sefinek24** [comment]
I've never published the Stella Mod on GameBanana. Apparently, someone had malicious intent and impersonated me by publishing the mod along with a virus.

Please make sure you scan the correct file. The Stella Mod installer is only published on Releases on Github. The correct link for scanning is: https://www.virustotal.com/gui/file/1f801f0cdd9b94abfecbe1d2ea8e389dd7c51151d75cc1bb3115cebcc3d5abcc

Regarding the GIMI paywall, please visit the following page: https://sefinek.net/genshin-impact-reshade/subscription and scroll to the bottom.

```
MD5	9b3d7198903cebc39aa0cb3fe17f18f7
SHA-1	c399265cc26de0769ce6abf5b366bf77d9742111
SHA-256	1f801f0cdd9b94abfecbe1d2ea8e389dd7c51151d75cc1bb3115cebcc3d5abcc
```

**Comment by sefinek24** [comment]
Continuing to analyze the details on VirusTotal, the file that is the virus hasn't even been compiled using InnoSetup.

![image](https://github.com/sefinek24/Genshin-Impact-ReShade/assets/92880265/ac91a196-a90c-440d-af4b-0b0e93b62b05)

My code for InnoSetup is available here: https://github.com/sefinek24/Genshin-Impact-ReShade/blob/main/InnoSetup/Setup.iss

**Comment by Scarlaid** [comment]
Yeah the misunderstanding bout the malicious attempt was clear, sorry 'bout that

The Patreon payment was a bit confusing, Tier 2 said about GIMI going with Stella while the ending statement said it is "a gratitue of support"
Thats the main thing I dont understand, I see GIMI can be injected through `d3d11.dll` easily, GI FPSUnlocker did it at ease

Is this a misinformation on accidental or on purpose?

**Comment by sefinek24** [comment]
This website is not yet finished. There are mentions of Patreon, which we no longer use. I will make the necessary updates in my free time. Thank you for letting me know about everything
