### ISSUE TITLE
New UI — Just as example

### ISSUE THREAD

**Issue by alexpado** [sefinek24/Genshin-Impact-ReShade#39]
Hi!

First, thank you for the launcher. Being able to use reshade on Genshin is very nice!

I had an hour to kill and did this small ui prototype using Figma. It was just an idea that went through my head on the moment, and if you are interested we could work together on a complete version of it.

I don't know how far you can go using ~~WinForms~~ WPF in C#, but we could find solution I guess :)

![Launcher](https://github.com/sefinek24/Genshin-Impact-ReShade/assets/31733699/062589c2-61f9-4aa5-bea3-3579b766451a)

I can change the orange color if needed (as it seems you like blue a lot)

**Comment by sefinek24** [comment]
Hi. Thanks for appreciating my work, @alexpado 

The prototype looks nice.

WinForms are quite limited; the best solution is to use WPF. WPF applications are considered more professional. It would be great to rewrite Stella Mod to .NET 8 as well.
Unfortunately, I'm unable to work on Stella Mod at the moment.

Any contribution is welcome (;

**Comment by alexpado** [comment]
Well, I'm used to work with web languages and I didn't really worked with WPF before. I did few apps in WinForms around 8 years ago though (that's as far as my C# knowledges stops)

Now, when it comes to desktop app, I'm mostly working with electron which allows me to use HTML, CSS and JS.

As I can see, WPF seems to be just another variant of XML, so I shouldn't have too much trouble with it as long as I'm not going into complex stuff (plus, Visual Studio have a nice UI building tool). I'll try to design few components using WPF to see how far can I go and adapt the prototype if necessary.

I still have few question about the launcher before going further into designing stuff:

**Do you want to keep non-genshin related windows / menu ?**
While exploring all the links available in the launcher I noticed, for example, that the Paimon picture in the bottom right open a window letting you view random pictures. Same goes for the `click me ;w;` just above.

**Do you have any preferences on color / layout ?**
It's still your launcher, after all. I don't want to impose my design choices on you, I just want to enhance the UX.

**Comment by sefinek24** [comment]
1. It would be nice to keep the previous windows from the current launcher.
2. Do as you like. You can base it on the color blue.

**Comment by ethurieal** [comment]
How do you get shaders?????? the only links i see is for mods lmfao this is so confusing

**Comment by sefinek24** [comment]
The [README.md](https://github.com/sefinek24/Genshin-Impact-ReShade/blob/main/README.md) file contains an image with the text `DOWNLOAD`
