### ISSUE TITLE
FPS Unlocker doesn't work after game update

### ISSUE THREAD

**Issue by Epikest** [sefinek24/Genshin-Impact-ReShade#40]
### Describe the bug
title

### To Reproduce
1. use Genshin Impact 4.4
2. update to 4.5

### Expected behavior
fps unlocker should work.

### Screenshots
![image](https://github.com/sefinek24/Genshin-Impact-ReShade/assets/45499416/3286e049-4e1f-4cb1-b4c3-7a837a4f0b4f)

### Desktop
- **OS:** Windows 10 22H2
- **Build:** 19045.2846
- **Stella version:** v8.0.0.2

**Comment by sefinek24** [comment]
Fixed in v8.0.1.0

https://sefinek.net/genshin-impact-reshade/docs?page=changelog_v8#ver-801
