### ISSUE TITLE
FPS Unlocker `UsePowerSave` sometimes doesn't recognize focus change

### ISSUE THREAD

**Issue by Epikest** [sefinek24/Genshin-Impact-ReShade#41]
### Describe the bug
the option `UsePowerSave` in FPS Unlocker sometimes fails to uncap the fps after returning focus to the Genshin Impact window.

### To Reproduce
1. set `"UsePowerSave": true` in `unlocker.config.json`
2. start the game with the FPS Unlocker
3. try `ALT`+`TAB`ing a couple times
4. when the game window is focused the FPS could be locked to save power

Alternative method:
1. click "Start game" in Stella Mod Launcher
2. when the terminal window opens, click onto any maximized window to make it lose focus
3. game will open and should be unfocused in the background
4. upon `ALT`+`TAB` into the Genshin Impact window, the FPS will still be capped at the "START GAME"/"Login" page

### Expected behavior
power draw reduced when window not focused, power draw increased when window focused.

### Screenshots
![image](https://github.com/sefinek24/Genshin-Impact-ReShade/assets/45499416/ec08d3e3-5baa-41b6-a119-0c9a1d754084)

### Desktop
- **OS:** Windows 10 22H2
- **Build:** 19045.2846
- **Stella version:** v8.0.1.0

### Additional context
most commonly occurs right after the Stella Mod terminal window closes and the Genshin Impact process starts.

**Comment by sefinek24** [comment]
I will look into it soon

**Comment by sefinek24** [comment]
This issue has been resolved. The fix will be available in the upcoming version
