### ISSUE TITLE
We need Chinese, thank you

### ISSUE THREAD

**Issue by shiolife** [sefinek24/Genshin-Impact-ReShade#42]

**Comment by sefinek24** [comment]
I am neither from Asia nor China, and I do not speak any Chinese. Stella Mod is primarily developed for English, and to some extent Polish (from my side). If anyone wishes to create their own translations into their native language, I am open to that. I will soon try to make the translation files available.

See: https://github.com/sefinek24/Stella-Mod-Translations

**Comment by shiolife** [comment]
在中国的AMD显卡用户会对Stella Mod 很感兴趣，并且我也不会英文 = =

**Comment by shiolife** [comment]
在中国的AMD显卡用户会对Stella Mod 很感兴趣，而我也不会英文
AMD graphics card users in China will be very interested in Stella Mod, and I don't speak English.

**Comment by sefinek24** [comment]
AMD graphics cards are compatible with Stella Mod and should work without any problems.
