### ISSUE TITLE
503 (Service Unavailable)

### ISSUE THREAD

**Issue by Epikest** [sefinek24/Genshin-Impact-ReShade#46]
### Describe the bug
Stella Mod servers are down and this prevents you from launching the game.

### To Reproduce
1. open Stella Mod Launcher

### Expected behavior
you should be able to launch the game irregardless of a successful update check.

### Screenshots
![image](https://github.com/sefinek24/Genshin-Impact-ReShade/assets/45499416/e88f1ccb-b1f5-4dd3-9a51-04cf5f0a1d04)

### Desktop
- **OS:** Windows 10 22H2
- **Build:** 19045.2846
- **Stella version:** v8.0.1.0

### Additional context
here's the response that appears in Stella Mod Launcher:
```json
{
    "success": false,
    "status": 503,
    "message": "The service is currently unavailable. The reasons can vary, such as server overload, configuration errors, or scheduled maintenance. Please try again later or contact the administrator if the problem persists. You can also check the status page at https://status.sefinek.net."
}
```
the server doesn't have the best uptime:
![image](https://github.com/sefinek24/Genshin-Impact-ReShade/assets/45499416/f4af8af7-e9b8-4d3b-a023-8b8592256e1a)

**Comment by sefinek24** [comment]
I am currently migrating DNS from Pi-hole to AdGuard because the Pi-hole devs are incompetent

**Comment by Epikest** [comment]
> I am currently migrating DNS from Pi-hole to AdGuard because the Pi-hole devs are incompetent

i think you should also show the "Start game" button at all times and display a warning if Stella Mod can't check for updates.

**Comment by sefinek24** [comment]
For security reasons, your request cannot be fulfilled. Before allowing the game to launch, the server must authorize the client's request
