### ISSUE TITLE
Newer version of windows terminal installed

### ISSUE THREAD

**Issue by Esdeath79** [sefinek24/Genshin-Impact-ReShade#49]
Hi there,
during the install I get an error message, that the setup is trying to install the latest windows terminal, but since a newer version is installed, it will result in an error.

`Command execution failed because the underlying process (powershell) returned a non-zero exit code - 1.
Check your Internet connection, antivirus program or restart PC and try again.

» Executed command:
powershell Add-AppxPackage -Path "dependencies\Microsoft.WindowsTerminal_1.19.10573.0_8wekyb3d8bbwe.msixbundle"

» Working directory: C:\Program Files\Sefinek\Genshin-Stella-Mod\net8.0-windows\

» Exit code: 1

» Error [stderr]:
Add-AppxPackage : Deployment failed with HRESULT: 0x80073D06, The package could not be installed because a higher
version of this package is already installed.
Das Paket "Microsoft.WindowsTerminal_1.19.10573.0_x64__8wekyb3d8bbwe" kann nicht installiert werden, da es die Version
1.19.10573.0 aufweist. Die h�here Version 1.20.11381.0 dieses Pakets ist bereits installiert.
NOTE: For additional information, look for [ActivityId] ae514fad-be39-0004-2f03-55ae39beda01 in the Event Log or use
the command line Get-AppPackageLog -ActivityID ae514fad-be39-0004-2f03-55ae39beda01
At line:1 char:1`

**Comment by sefinek24** [comment]
Uninstall the windows terminal from the MS Store.
