### ISSUE TITLE
Genshin Impact Stella Mod - Prepare Fail

### ISSUE THREAD

**Issue by thechampof100** [sefinek24/Genshin-Impact-ReShade#51]
Genshin Impact Stella Mod - Prepare
                                        Version: v2.0.0.0

» Author  : Sefinek [Country: Poland]
» Website : https://genshin.sefinek.net
» Discord : https://discord.gg/k2wfGRq4dT
===============================================================================================

-- Select the correct localizations --
» Game path: C:\Program Files\miHoYo Launcher\games\Genshin Impact Game\YuanShen.exe
» Resources: C:\Stella-Mod-Resources

-- Run the final configuration --
Starting...
Checking Stella resources...
Found: C:\Stella-Mod-Resources
Checking current version of resources... v1.4.0 (stable) from 2024-01-19T16:42:00.000Z
Deleting C:\Stella-Mod-Resources\Temp files\Stella Mod Resources - v1.4.0.zip...
Downloading Stella Mod resources... 48922414.48922414 bytes (100%) at 8674.29 KB/s
Waiting for resources to be disposed...
Unpacking resources...
Prepare ReShade...
Downloading ReShade.ini (5631 bytes)...
Downloading ReShade.log (Unknown file size)...
Something went wrong. Config or log file for ReShade was not found in: C:\Program Files\miHoYo Launcher\games\Genshin Impact Game  
can‘t Downloading ReShade.log

**Comment by sefinek24** [comment]
The new launcher (HoYoPlay) can be incompatible, you need to configure stella manually in the system registry
![image](https://github.com/sefinek24/Genshin-Impact-ReShade/assets/92880265/6a514999-6d07-44ab-a412-496bd2bf1386)

ReShade.ini you can download from this url https://github.com/sefinek24/Stella-Mod-Resources/tree/main/public/static/reshade

**Comment by thechampof100** [comment]
> The new launcher (HoYoPlay) is incompatible, you need to configure stella manually in the system registry ![image](https://private-user-images.githubusercontent.com/92880265/346333279-6a514999-6d07-44ab-a412-496bd2bf1386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjQzMTcsIm5iZiI6MTcyMDM2NDAxNywicGF0aCI6Ii85Mjg4MDI2NS8zNDYzMzMyNzktNmE1MTQ5OTktNmQwNy00NGFiLWE0MTItNDk2YmQyYmYxMzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE0NTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NWQ3YzNkMGE5ZmYxMTM1NWJlMzEyN2RmYzZmMjIzNmNmNTUzZmQyMGI1ZTczOGZlZDJiODFmMDViZDkxYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G6xccg8CgT1WqiVugA_P_9X-eb-v6vheOlQO3g-VNBc)
> 
> ReShade.ini you can download from this url https://github.com/sefinek24/Stella-Mod-Resources/tree/main/public/static/reshade

I created a blank file and named it ReShade.log then it worked. now the problem is that the fps unlocker doesn't work. When I start initiate the game, it is working. But later it go back to 60fps.

**Comment by sefinek24** [comment]
8.0.1.0 is outdated - it is the version from March. The latest version, which includes important updates and bug fixes, was released in June. If you want to stay current with all the latest features and improvements, you can either wait for the global update to be rolled out or consider purchasing Stella Plus, which provides immediate access to the most recent updates.

To be honest, I don't really care about compatibility with YuanShen because I'm not from China.

Good luck, and I hope you find a solution that works for you!

**Comment by thechampof100** [comment]
> 8.0.1.0 is outdated - it is the version from March. The latest version, which includes important updates and bug fixes, was released in June. If you want to stay current with all the latest features and improvements, you can either wait for the global update to be rolled out or consider purchasing Stella Plus, which provides immediate access to the most recent updates.
> 
> To be honest, I don't really care about compatibility with YuanShen because I'm not from China.
> 
> Good luck, and I hope you find a solution that works for you!

Thank you, I have founded a solution.
