### ISSUE TITLE
Add new ReShade Effect to us be able to use Genshin in 3D on VR by default installed and disabled

### ISSUE THREAD

**Issue by Kaponyt** [sefinek24/Genshin-Impact-ReShade#53]
### Is your feature request related to a problem? Please describe.
I managed to run Genshin in 3D on Quest2 adding an effect from ReShade on Stella. I wish more people could do this without having to deal with so many more settings (I had never messed with this before and it took me a long time to adjust all the settings on Stella). That's why I would like to ask to add a ReShade effect called "SuperDepth3D_VR" to Stella's default options, it can be disabled by default.

### How to do it:
- From "https://reshade.me/", download the "[Download ReShade 6.3.1](https://reshade.me/downloads/ReShade_Setup_6.3.1.exe)" (or newer version)
- Open it, select the Genshin executable file
- Select "DirectX 10,11,12"
- Install Deph3D:
![image](https://github.com/user-attachments/assets/8cd33055-3597-438a-b4da-5b527c91635d)
- Copy "SuperDepth3D_VR+.fx" from ReShade shaders inside genshin installation folder
- Paste in "Stella-Mod-Resources\ReShade\Shaders\Effects"
- change "Stella-Mod-Resources\ReShade\Presets\1. Default preset - Medium settings.ini", in "TechniqueSorting" add "SuperDepth3D_VR@SuperDepth3D_VR+.fx"

### Make it work on any VR:
In fact we need to follow this kinda complex tutorial:
https://www.youtube.com/watch?v=dtWNAaVLay8
But instead opening Genshin by itself, need to use Stella

### Describe alternatives you've considered
I tried using pure ReShade, but Genshin won't open, luckily I found this project

### Additional context
It's really cool to run Genshin in 3D, and using Reshade it's free.

**Comment by sefinek24** [comment]
Honestly, I don't think it's necessary.
